### ISSUE TITLE
JSON parsing error

### ISSUE THREAD

**Issue by jaxxstorm** [PagerDuty/lita-pagerduty#25]
When running any query, I'm getting a JSON parse issue:

```
[2017-02-05 12:01:14 UTC] ERROR: Lita::Handlers::PagerdutyUtility crashed. The exception was:
743: unexpected token at ''
Full backtrace:
/vendor/bundle/ruby/2.3.0/gems/json-2.0.3/lib/json/common.rb:156:in `parse'
/vendor/bundle/ruby/2.3.0/gems/json-2.0.3/lib/json/common.rb:156:in `parse'
/vendor/bundle/ruby/2.3.0/gems/pagerduty-sdk-1.0.9/lib/pagerduty/core.rb:79:in `curl'
/vendor/bundle/ruby/2.3.0/gems/pagerduty-sdk-1.0.9/lib/pagerduty/pagerduty.rb:883:in `get_schedules'
/vendor/bundle/ruby/2.3.0/bundler/gems/lita-pagerduty-cb796fa02423/lib/lita/handlers/pagerduty_utility.rb:62:in `on_call_list'
/vendor/bundle/ruby/2.3.0/gems/lita-4.7.1/lib/lita/callback.rb:31:in `public_send'
/vendor/bundle/ruby/2.3.0/gems/lita-4.7.1/lib/lita/callback.rb:31:in `call'
/vendor/bundle/ruby/2.3.0/gems/lita-4.7.1/lib/lita/handler/chat_router.rb:97:in `dispatch_to_route'
/vendor/bundle/ruby/2.3.0/gems/lita-4.7.1/lib/lita/handler/chat_router.rb:82:in `block in dispatch'
/vendor/bundle/ruby/2.3.0/gems/lita-4.7.1/lib/lita/handler/chat_router.rb:72:in `map'
/vendor/bundle/ruby/2.3.0/gems/lita-4.7.1/lib/lita/handler/chat_router.rb:72:in `dispatch'
/vendor/bundle/ruby/2.3.0/gems/lita-4.7.1/lib/lita/robot.rb:69:in `block in receive'
/usr/local/lib/ruby/2.3.0/set.rb:306:in `each_key'
/usr/local/lib/ruby/2.3.0/set.rb:306:in `each'
/vendor/bundle/ruby/2.3.0/gems/lita-4.7.1/lib/lita/robot.rb:66:in `map'
/vendor/bundle/ruby/2.3.0/gems/lita-4.7.1/lib/lita/robot.rb:66:in `receive'
/vendor/bundle/ruby/2.3.0/bundler/gems/lita-slack-7af55c22aed7/lib/lita/adapters/slack/message_handler.rb:123:in `dispatch_message'
/vendor/bundle/ruby/2.3.0/bundler/gems/lita-slack-7af55c22aed7/lib/lita/adapters/slack/message_handler.rb:160:in `handle_message'
/vendor/bundle/ruby/2.3.0/bundler/gems/lita-slack-7af55c22aed7/lib/lita/adapters/slack/message_handler.rb:18:in `handle'
/vendor/bundle/ruby/2.3.0/bundler/gems/lita-slack-7af55c22aed7/lib/lita/adapters/slack/rtm_connection.rb:100:in `block in receive_message'
/vendor/bundle/ruby/2.3.0/bundler/gems/lita-slack-7af55c22aed7/lib/lita/adapters/slack/event_loop.rb:10:in `block in defer'
/vendor/bundle/ruby/2.3.0/gems/eventmachine-1.2.2/lib/eventmachine.rb:1076:in `block in spawn_threadpool'
```

**Comment by esigler** [comment]
Thanks for the report!  Looking into it now.

**Comment by jaxxstorm** [comment]
Let me know if there's anything I can do to help.

**Comment by rhoml** [comment]
Any news on this?
